services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: ./producer
    volumes:
      - ./rabbitmq:/usr/src/app/rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3000:3000"

  consumer:
    build:
      context: ./consumer
    volumes:
      - ./rabbitmq:/usr/src/app/rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy